# Site settings
title: Shanya Sharma
general_email: sharmashanya1297@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  "Any sufficiently advanced technology is indistinguishable from magic."

baseurl: "" # the subpath of your site, e.g. /blog/

url: "thechange.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: GitHub
linkedin_username: LinkedIn
twitter_username: Twitter
google_scholar: Google Scholar
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
